# Generated by Django 5.2.3 on 2025-06-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('HP', models.IntegerField()),
                ('ATK', models.IntegerField()),
                ('DEF', models.IntegerField()),
                ('ER', models.IntegerField(default=100)),
                ('critRate', models.IntegerField(default=5)),
                ('critDMG', models.IntegerField(default=150)),
            ],
        ),
    ]
