# Generated by Django 5.2.3 on 2025-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiProj', '0002_rename_atk_characterstats_base_atk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='weaponStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('rarity', models.IntegerField()),
                ('base_ATK', models.IntegerField()),
                ('secondary_Stat', models.CharField(max_length=100)),
                ('secondary_Val', models.FloatField(default=0.0)),
                ('ATK', models.FloatField(default=0.0)),
                ('HP', models.FloatField(default=0.0)),
                ('DEF', models.FloatField(default=0.0)),
                ('ER', models.FloatField(default=0.0)),
                ('critRate', models.FloatField(default=0.0)),
                ('critDMG', models.FloatField(default=0.0)),
                ('rSkillDMG', models.FloatField(default=0.0)),
                ('bATKDMG', models.FloatField(default=0.0)),
                ('hATKDMG', models.FloatField(default=0.0)),
                ('rLibDMG', models.FloatField(default=0.0)),
                ('elemDMG', models.FloatField(default=0.0)),
                ('healBONUS', models.FloatField(default=0.0)),
            ],
        ),
    ]
