# Generated by Django 5.2.3 on 2025-06-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiProj', '0003_weaponstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponstats',
            name='dupes',
            field=models.IntegerField(default=1),
        ),
    ]
